# Configuration file used by the pipeline hydration step
# to render the manifests for the different environments
releaseName: &name kyverno
namespace: *name
environments:
  local:
    apis: &apis
    - cert-manager.io/v1
    - flowcontrol.apiserver.k8s.io/v1
    - flowcontrol.apiserver.k8s.io/v1beta1
    - flowcontrol.apiserver.k8s.io/v1beta2
    - flowcontrol.apiserver.k8s.io/v1beta3
    - kyverno.io/v1
    - kyverno.io/v2
    - policy/v1/PodDisruptionBudget
    - rbac.authorization.k8s.io/v1
    valueFiles:
    - values-subchart-overrides.yaml
    - values-local.yaml
  sf-k8s01-dev:
    apis: *apis
    valueFiles: &devValues
    - values-subchart-overrides.yaml
    - values-development.yaml
  sf-k8s02-dev:
    apis: *apis
    valueFiles: *devValues
  sf-k8s01-prod:
    apis: *apis
    valueFiles:
    - values-subchart-overrides.yaml
    - values-production.yaml
