kyverno:
  cleanupController:
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
          - batch
          - extensions
          resources:
          - jobs
          verbs:
          - get
          - delete
          - list
