kyverno:
  admissionController:
    replicas: 3
    container:
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 512Mi
  backgroundController:
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
            - ''
          resources:
            - secrets
          # we're using generate policies to clone secrets, so we need to
          # set these verbs according to https://main.kyverno.io/docs/installation/customization/#customizing-permissions
          verbs:
            - get
            - create
            - delete
            - list
            - update
            - view
            - watch
        - apiGroups:
            - cert-manager.io
          resources:
            - issuers
          verbs:
            - create
            - update
            - patch
            - delete
        - apiGroups:
            - acid.zalan.do
          resources:
            - postgresqls
          verbs:
            - list
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 160Mi
      requests:
        cpu: 50m
        memory: 80Mi
  cleanupController:
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
          - batch
          - extensions
          resources:
          - jobs
          verbs:
          - get
          - delete
          - list
    resources:
      limits:
        cpu: 200m
        memory: 96Mi
      requests:
        cpu: 20m
        memory: 48Mi
  reportsController:
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 96m
        memory: 192Mi
