kyverno:
  admissionController:
    container:
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 512Mi
    priorityClassName: &systemClusterCritical system-cluster-critical
    replicas: 3
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
          - ''
          resources:
          - secrets
          verbs:
          - get
          - list
        - apiGroups:
          - acid.zalan.do
          resources:
          - postgresqls
          verbs:
          - get
          - list
        - apiGroups:
          - networking.istio.io
          resources:
          - sidecars
          verbs:
          - get
          - list
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - get
          - list
        - apiGroups:
          - security.istio.io
          resources:
          - peerauthentications
          verbs:
          - get
          - list
  backgroundController:
    priorityClassName: *systemClusterCritical
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
          - acid.zalan.do
          resources:
          - postgresqls
          verbs:
          - get
          - list
        - apiGroups:
            - cert-manager.io
          resources:
            - issuers
          verbs:
            - create
            - update
            - patch
            - delete
        - apiGroups:
          - networking.istio.io
          resources:
          - sidecars
          verbs:
          - create
          - delete
          - get
          - list
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - update
        - apiGroups:
          - security.istio.io
          resources:
          - peerauthentications
          verbs:
          - create
          - delete
          - get
          - list
          - update
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 160Mi
      requests:
        cpu: 50m
        memory: 80Mi
  cleanupController:
    priorityClassName: *systemClusterCritical
    rbac:
      clusterRole:
        extraResources:
        - apiGroups:
          - batch
          - extensions
          resources:
          - jobs
          verbs:
          - delete
          - get
          - list
    resources:
      limits:
        cpu: 200m
        memory: 96Mi
      requests:
        cpu: 20m
        memory: 48Mi
  cleanupJobs:
    admissionReports:
      resources:
        limits:
          cpu: 300m
          memory: 24Mi
        requests:
          cpu: 10m
          memory: 16Mi
    clusterAdmissionReports:
      resources:
        limits:
          cpu: 300m
          memory: 24Mi
        requests:
          cpu: 10m
          memory: 16Mi
    clusterEphemeralReports:
      resources:
        limits:
          cpu: 300m
          memory: 24Mi
        requests:
          cpu: 10m
          memory: 16Mi
    ephemeralReports:
      resources:
        limits:
          cpu: 300m
          memory: 24Mi
        requests:
          cpu: 10m
          memory: 16Mi
    updateRequests:
      resources:
        limits:
          cpu: 300m
          memory: 24Mi
        requests:
          cpu: 10m
          memory: 16Mi
  config:
    enableDefaultRegistryMutation: false
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
  features:
    admissionReports:
      # -- Enables the feature
      enabled: false
    logging:
      format: json
      verbosity: -1
    policyExceptions:
      enabled: true
      namespace: "*"
  networkPolicy:
    enabled: true
  reportsController:
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 96m
        memory: 192Mi
  # Disabled since Argo CD currently do not support pre-delete Helm hooks
  # See https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks
  webhooksCleanup:
    enabled: false
