{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/name: kyverno
    app: kyverno
  name: kyverno:generate-issuer
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - update
  - patch
  - delete
{{- end }}
{{- end }}
